package br.sp.unifae.cris.comp7.model;
// Generated 01/05/2017 22:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nome;
     private String fisicaOuJuridica;
     private String cpfOuCnpj;
     private String endereco;
     private String cidade;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(Estado estado, String nome, String fisicaOuJuridica, String cpfOuCnpj, String endereco, String cidade, Set vendas) {
       this.estado = estado;
       this.nome = nome;
       this.fisicaOuJuridica = fisicaOuJuridica;
       this.cpfOuCnpj = cpfOuCnpj;
       this.endereco = endereco;
       this.cidade = cidade;
       this.vendas = vendas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getFisicaOuJuridica() {
        return this.fisicaOuJuridica;
    }
    
    public void setFisicaOuJuridica(String fisicaOuJuridica) {
        this.fisicaOuJuridica = fisicaOuJuridica;
    }
    public String getCpfOuCnpj() {
        return this.cpfOuCnpj;
    }
    
    public void setCpfOuCnpj(String cpfOuCnpj) {
        this.cpfOuCnpj = cpfOuCnpj;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


