package br.sp.unifae.cris.comp7.model;
// Generated 01/05/2017 22:04:39 by Hibernate Tools 4.3.1



/**
 * EntradaProdutoId generated by hbm2java
 */
public class EntradaProdutoId  implements java.io.Serializable {


     private int idEntrada;
     private int item;

    public EntradaProdutoId() {
    }

    public EntradaProdutoId(int idEntrada, int item) {
       this.idEntrada = idEntrada;
       this.item = item;
    }
   
    public int getIdEntrada() {
        return this.idEntrada;
    }
    
    public void setIdEntrada(int idEntrada) {
        this.idEntrada = idEntrada;
    }
    public int getItem() {
        return this.item;
    }
    
    public void setItem(int item) {
        this.item = item;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntradaProdutoId) ) return false;
		 EntradaProdutoId castOther = ( EntradaProdutoId ) other; 
         
		 return (this.getIdEntrada()==castOther.getIdEntrada())
 && (this.getItem()==castOther.getItem());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEntrada();
         result = 37 * result + this.getItem();
         return result;
   }   


}


