package br.sp.unifae.cris.comp7.model;
// Generated 01/05/2017 22:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Formapagamento generated by hbm2java
 */
public class Formapagamento  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set vendas = new HashSet(0);

    public Formapagamento() {
    }

    public Formapagamento(String nome, Set vendas) {
       this.nome = nome;
       this.vendas = vendas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


