package br.sp.unifae.cris.comp7.model;
// Generated 01/05/2017 22:04:39 by Hibernate Tools 4.3.1



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nome;
     private String fisicaOuJuridica;
     private String cpfOuCnpj;
     private String endereco;
     private String cidade;
     private Entrada entrada;

    public Fornecedor() {
    }

    public Fornecedor(Estado estado, String nome, String fisicaOuJuridica, String cpfOuCnpj, String endereco, String cidade, Entrada entrada) {
       this.estado = estado;
       this.nome = nome;
       this.fisicaOuJuridica = fisicaOuJuridica;
       this.cpfOuCnpj = cpfOuCnpj;
       this.endereco = endereco;
       this.cidade = cidade;
       this.entrada = entrada;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getFisicaOuJuridica() {
        return this.fisicaOuJuridica;
    }
    
    public void setFisicaOuJuridica(String fisicaOuJuridica) {
        this.fisicaOuJuridica = fisicaOuJuridica;
    }
    public String getCpfOuCnpj() {
        return this.cpfOuCnpj;
    }
    
    public void setCpfOuCnpj(String cpfOuCnpj) {
        this.cpfOuCnpj = cpfOuCnpj;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }




}


