package br.sp.unifae.cris.comp7.model;
// Generated 01/05/2017 22:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Formapagamento formapagamento;
     private Float totalVenda;
     private Set vendaProdutos = new HashSet(0);

    public Venda() {
    }

    public Venda(Cliente cliente, Formapagamento formapagamento, Float totalVenda, Set vendaProdutos) {
       this.cliente = cliente;
       this.formapagamento = formapagamento;
       this.totalVenda = totalVenda;
       this.vendaProdutos = vendaProdutos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Formapagamento getFormapagamento() {
        return this.formapagamento;
    }
    
    public void setFormapagamento(Formapagamento formapagamento) {
        this.formapagamento = formapagamento;
    }
    public Float getTotalVenda() {
        return this.totalVenda;
    }
    
    public void setTotalVenda(Float totalVenda) {
        this.totalVenda = totalVenda;
    }
    public Set getVendaProdutos() {
        return this.vendaProdutos;
    }
    
    public void setVendaProdutos(Set vendaProdutos) {
        this.vendaProdutos = vendaProdutos;
    }




}


