package br.sp.unifae.cris.comp7.model;
// Generated 01/05/2017 22:04:39 by Hibernate Tools 4.3.1



/**
 * VendaProduto generated by hbm2java
 */
public class VendaProduto  implements java.io.Serializable {


     private VendaProdutoId id;
     private Produto produto;
     private Venda venda;
     private Float quantidade;

    public VendaProduto() {
    }

	
    public VendaProduto(VendaProdutoId id, Venda venda) {
        this.id = id;
        this.venda = venda;
    }
    public VendaProduto(VendaProdutoId id, Produto produto, Venda venda, Float quantidade) {
       this.id = id;
       this.produto = produto;
       this.venda = venda;
       this.quantidade = quantidade;
    }
   
    public VendaProdutoId getId() {
        return this.id;
    }
    
    public void setId(VendaProdutoId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public Float getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Float quantidade) {
        this.quantidade = quantidade;
    }




}


